import {
  FileTextIcon,
  StickyNoteIcon,
  StarIcon,
  HeartIcon,
  FlagIcon,
  BookmarkIcon,
  LightbulbIcon,
  RocketIcon,
  TargetIcon,
  ZapIcon,
  CoffeeIcon,
  MusicIcon,
  CodeIcon,
  BookOpenIcon,
  CalendarIcon,
  CheckSquareIcon,
  FolderIcon,
  PencilIcon,
  BellIcon,
  GlobeIcon,
  BrainIcon,
  BriefcaseIcon,
  GraduationCapIcon,
  TerminalIcon,
  DatabaseIcon,
  Gamepad2Icon,
  FilmIcon,
  ImageIcon,
  CameraIcon,
  ShoppingCartIcon,
  DollarSignIcon,
  GiftIcon,
  TrophyIcon,
  LeafIcon,
  FlameIcon,
  DropletIcon,
  AnchorIcon,
  CompassIcon,
  MailIcon,
  PhoneIcon,
  ClockIcon,
  MapPinIcon,
  KeyIcon,
  LockIcon,
  ShieldIcon,
  SmileIcon,
  PaletteIcon,
  WrenchIcon,
  HammerIcon,
  PlaneIcon,
  CarIcon,
  TreePineIcon,
  SproutIcon,
  BugIcon,
  AtomIcon,
  MessageCircleIcon,
  ThumbsUpIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  LinkIcon,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const DEFAULT_NOTE_ICON = "FileText";


export const NOTE_ICONS: Record<string, LucideIcon> = {
  FileText: FileTextIcon,
  StickyNote: StickyNoteIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  Flag: FlagIcon,
  Bookmark: BookmarkIcon,
  Lightbulb: LightbulbIcon,
  Rocket: RocketIcon,
  Target: TargetIcon,
  Zap: ZapIcon,
  Coffee: CoffeeIcon,
  Music: MusicIcon,
  Code: CodeIcon,
  Book: BookOpenIcon,
  Calendar: CalendarIcon,
  CheckSquare: CheckSquareIcon,
  Folder: FolderIcon,
  Pencil: PencilIcon,
  Bell: BellIcon,
  Globe: GlobeIcon,
  Brain: BrainIcon,
  Briefcase: BriefcaseIcon,
  GraduationCap: GraduationCapIcon,
  Terminal: TerminalIcon,
  Database: DatabaseIcon,
  Gamepad: Gamepad2Icon,
  Film: FilmIcon,
  Image: ImageIcon,
  Camera: CameraIcon,
  Cart: ShoppingCartIcon,
  DollarSign: DollarSignIcon,
  Gift: GiftIcon,
  Trophy: TrophyIcon,
  Leaf: LeafIcon,
  Flame: FlameIcon,
  Droplet: DropletIcon,
  Anchor: AnchorIcon,
  Compass: CompassIcon,
  Mail: MailIcon,
  Phone: PhoneIcon,
  Clock: ClockIcon,
  MapPin: MapPinIcon,
  Key: KeyIcon,
  Lock: LockIcon,
  Shield: ShieldIcon,
  Smile: SmileIcon,
  Palette: PaletteIcon,
  Wrench: WrenchIcon,
  Hammer: HammerIcon,
  Plane: PlaneIcon,
  Car: CarIcon,
  TreePine: TreePineIcon,
  Sprout: SproutIcon,
  Bug: BugIcon,
  Atom: AtomIcon,
  MessageCircle: MessageCircleIcon,
  ThumbsUp: ThumbsUpIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Cloud: CloudIcon,
  Link: LinkIcon,
};

export const NOTE_ICON_KEYS = Object.keys(NOTE_ICONS);

export function noteIcon(key?: string | null): LucideIcon {
  return (key && NOTE_ICONS[key]) || NOTE_ICONS[DEFAULT_NOTE_ICON];
}

export interface NoteColor {
  label: string;
  value: string;
}

export const NOTE_COLORS: NoteColor[] = [
  { label: "Default", value: "" },
  { label: "Red", value: "#ef4444" },
  { label: "Orange", value: "#f97316" },
  { label: "Amber", value: "#f59e0b" },
  { label: "Green", value: "#22c55e" },
  { label: "Teal", value: "#14b8a6" },
  { label: "Blue", value: "#3b82f6" },
  { label: "Violet", value: "#8b5cf6" },
  { label: "Pink", value: "#ec4899" },
];

export function noteColor(color?: string | null): string | undefined {
  return color ? color : undefined;
}
